language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jirvingphd
  password:
    secure: iTLprNEXmAzapRgPQjrFzdgXftXK4z4oFeKULSjRPM8unPj2MEU4AP2f1NbJAeqEY/m2mOgiE5F3TkTsFDmdZKF4QAZ909Xn2xbTEXYlGFS4w2wDYjN/+jebOII7heHtT1oSc75u5WYU4f1iEWGAVVUrCJEx9DrrjU5okHn9Fv9+l7oHjELGlIXrU3j4YoOxgpev+HRJeiSpYHKHdiR2ECauVjKfeYvxWO6mbPzqjLU4eMr6rrxdhAbVCKE6rFiBjd68gzk99KLZQKsgUEBt1FqkkECCye//5hyOe8RuZ4LBKic/NOQOPbH6N8fnaQptCTJJ8U0Kiy1AuKk+P1SOlW/oIwbtnMzgpckELNZ3IiRpg5nCGBtlTfqqLfeoI83bO1EUiy0P5ruffbDZpQmN9FKN5PLSdwO3mZL37/HD/WrP9EzdLuCUGrUssJN8VXEO7v6BIwaVUToKOu9fdEE/RZdBRbmvCQVKNaLyrnNAEGT471VW8aQU5WpxS4+dQZ1ekq5n4ACHyWt3/1JLC6xVFyyIkoYzw4yi/UJSaEJA56EDv3+F1KoKLchKHbCK7V38+JL0nd4/7qZG2WqsJ0SN63QaqLLzqraMOpjA0vGBIOoEAo46NqxjfsbYp6U995wfQwS2fkwV1vKSgIepPQ7Z2iVeztgSYSy+D03+qhxq2zk=
  on:
    tags: true
    repo: jirvingphd/fsds_100719
    python: 3.6
